### ISSUE TITLE
数据处理

### ISSUE THREAD

**Issue by starletbb** [codeCyw/DC2R#1]
冒昧打扰，请问作者可以提供数据处理的细节和代码吗

**Comment by codeCyw** [comment]
感谢关注我们的工作！
1. 实际上，Grocery及Yelpsmall数据集来自https://github.com/Ee1s/NirGNN, 这两个数据集的处理可以参考NirGNN原文。
2. 我处理的数据集是CellPhones，不过距离处理数据集已过去一年，代码已经遗失，我可以描述数据处理过程，如有不清楚之处可以继续询问。
3. 处理CellPhones数据集时，item的品牌、价格、类别按照https://github.com/Zhang-xiaokun/MMSBR/tree/main/MMSBR 中的方式处理（将文字类型的品牌、类别进行编号，价格进行归一化）。处理完后每个物品有2个attr信息（品牌、价格），3个类别信息(数据集中一个物品默认有3个类别)，将这些辅助信息以SessionID, ItemID, attr1, attr2, taxo1, taxo2, taxo3为列的形式存储于csv中，最终生成会话时，利用此csv构造会话中每个物品对应的attr及taxo信息即可。
4. 生成会话时新物品的处理。参考NirGNN，我对new item的定义是在所有会话中都没有出现过的物品。即，当一个物品i作为ground truth时，遍历所有会话，删除其中的i。
