### ISSUE TITLE
关于新项目的定义

### ISSUE THREAD

**Issue by onetance** [codeCyw/DC2R#2]
您好，我想请教一下文中对新项目的定义：
请问对于一个固定的会话
新项目是指未曾出现在所有用户历史会话中的项目，
还是只是 未曾出现在当前固定会话中的项目。

**Comment by codeCyw** [comment]
感谢关注我们的工作！
新项目是指未曾出现在所有用户历史会话中的项目。即，当一个物品i作为ground truth时，遍历所有会话，删除其中的i。

**Comment by onetance** [comment]
> 感谢关注我们的工作！ 新项目是指未曾出现在所有用户历史会话中的项目。即，当一个物品i作为ground truth时，遍历所有会话，删除其中的i。

感谢您的回复，非常的有帮助
